#!/bin/sh

parseDirectory(){
  tmp="${1# }"
  echo "${tmp%/}"
}

selectBookmark(){

  SELECTION=$(cut -d ',' -f 1 "$BOOKMARK_DIR/$1" | dmenu -p "Choose a bookmark:" -l 10)

  if [ -z "$SELECTION" ]; then
    exit 0
  fi

  case "$SELECTION" in
    */)
      URL=$(selectBookmark $(parseDirectory "$SELECTION"))
      ;;
    *)
      URL=$(grep "$SELECTION" "$BOOKMARK_DIR/$1" | cut -d ',' -f 2)
      ;;
  esac

  echo "$URL"
}

BOOKMARK_DIR="/home/darkskoll/.bin/bookmarks"

"$BROWSER" $(selectBookmark "top") &
