#!/bin/sh

case $1 in
  up)
    pactl set-sink-volume @DEFAULT_SINK@ +5%
    ;;
  down)
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    ;;
  mute)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    ;;
esac

dunsctl close-all
VOLUME=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -E -o '[0-9]{1,3}%' | uniq)
notify-send 'Vol:' -h int:value:"$VOLUME"
