#!/bin/sh

BOOKMARKS_FILE="$HOME/.local/share/bookmarks"

selection=$(cut -d ',' -f 1 "$BOOKMARKS_FILE" | dmenu -i -l 10 -p "Choose a page")

if [ -z "$selection" ]; then
  exit
fi

url=$(grep "$selection" "$BOOKMARKS_FILE" | cut -d ',' -f 2)

"$BROWSER" "$url"


